"""
Django settings for axf project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wv1k&fr_ceonu=kvv-a%rws#2w0^4c$0r3-hzh(sk1*9x%cn4^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'corsheaders',
    'goods',
    'rest_framework',
    'django_filters',
    'cart',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 跨域请求中间件
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'axf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'axf.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'axfrest',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {'isolation_level': None}
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# 跨域
CORS_ALLOW_METHODS = (
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
)
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

# rest framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'utils.renderers.CustomJsonRender',
    ),
    # # 定义过滤配置
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

# 数据库的缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # 存储数据的格式为str，而不是bytes格式
            'CONNECTION_POOL_KWARGS': {'decode_responses': True}
        }
    }
}

# 支付宝相关配置
ALIPAY_APPID = "2016091800537304"

APP_PRIVATE_KEY = """
MIIEowIBAAKCAQEAwzNeBKT1JGWQMkYWwtWhbIeojjAh5JhRsEnJ9z7nq3P0O0Id
1E135lFgSfU83MfGhXYyoaNVcQ85dBHEemxbPYT3yxGoPRv5/bt8e8zOwQu5fiF3
IrTuLQ+4fNfHO0tJGmRfCwW3h/hM7EEOLZfybZrodg95QqrqEoLpTMx5toAUqwZI
L8e+QFrvh6+rid1WJ6YJl1kimFccfUDOnWgbEp5cNhARSsO1xb86x4YHD6MPvfOj
E+Q7wmCqblj8PDPQdKZIu4a78hPVpUv4pUE6lzpeXo4ez92mgpizHjV+43O3sEcg
SuiAdUp3XP/F67jgaSrJF+f5OfABLh+MbF4AhwIDAQABAoIBAFEYVxgA3CNZ2nU4
bx5UmHK5TUp9LqeErHNbxH9mb+LoEnBIAJKB+K0D48f2DWn/yTcLKu/CJq4I0Cqr
cwAVYjaFtlh0Jnv00oAaUxYvuTm0QETpbFBL8KNh45hiINA+b8l6J44xutTPUE3a
nSRN+xaUA72AojUTQpmcL4aLcIljo9v2ugmMsmIEYc1o9JdvK1FblSBomGRrjh9U
A/AUMYNj79DnnsQxmYLCfJS3Bc6tEFH0EJefsFCrW9kT6yVCmP9r1KrdMt7Lu8M/
MGTiq0xyoeuRv/eQfp+B3GDoNaavzdS6AxCn0SpPdmG0LWFHi1yfHHavtDUiXIoo
RvYG/dECgYEA+S51XjaxSozFh/79/A/b23lWJhuFkV6VV0GMhfjreE04qRsU+MBb
NnHPrCN/9qRIG579cdw8F4u12oBaDGIJJM53WonoSvCbG6/Q5maRTvhnH8RnaAIy
dQRpIIzb0H1gqREHcvffIDoCK9XyUx5DX0VzXlRq9ypDLAnpAakh4wkCgYEAyIrE
g7WlhR4T6AxgniAcg3ecEmu0MXiab1o99ggpKjUmfDJZ51boWrrwfoXm6xqbwVQv
a3MYqTK7DgTr0daFXSq4u00kHkiAU+VMs6ytHeJ8WAPY2PWf7W2+7ra6ljxGvy9y
JrjnVz3ctx41zYqIgDA1NhymZgeG+0EIgbIh2w8CgYEAlXw9hOuiqGqTBeb/T3vk
FWJRQEM6ed8YEGSOfMC74kvRNgG9Lw2Wqq7UOxyA4+HiME/NE8Vfd3ClBBQD8XHO
snn6OCKLbImzQ4TR+aaGfa2fj/svXcITqweeWZynMghFOKeypFH3VUn3i3yqBxsc
p8buUySpluWPrpezZP+mCKECgYB08X8BM0bvZofDNJyO+TjHbVOE5muwwZyFPMGP
HFks9MuZdx84KVTbu9GMZncvOFgFmBsC9J435I5x8Wq29frVRpltF+HtCuhShA+D
YzmciLtr8+pbMnjtUqcZu1L5UvMKgBd3/zFgjYGNAz/quVM6NWKCSJi8PL14/QaB
4yec/wKBgEb6EvcRD+YVVKCvP+OapGBZYVeeo0sU5LVUQAiUV3zB/GrqMgcU6qDX
hzhBTLMcSVVgtzCglLZX1TRITVfG9DE6BZFBgXLWuMywJxKWe3f3FUjWu/WvAf2E
ytwQw9AbP7E5sm/TKbM7gLcnobX/rgr4mCFzYEjm88fdxhE5dUmj
"""

ALIPAY_PUBLIC_KEY = """
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIgHnOn7LLILlKETd6BFRJ0GqgS2Y3mn1wMQmyh9zEyWlz5p1zrahRahbXAfCfSqshSNfqOmAQzSHRVjCqjsAw1jyqrXaPdKBmr90DIpIxmIyKXv4GGAkPyJ/6FTFY99uhpiq0qadD/uSzQsefWo0aTvP/65zi3eof7TcZ32oWpwIDAQAB
-----END PUBLIC KEY-----
"""
