# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FruitServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品名录'},
        ),
        migrations.AlterModelOptions(
            name='goodstypeone',
            options={'verbose_name': '一级目录'},
        ),
        migrations.AlterModelOptions(
            name='goodstypetwo',
            options={'verbose_name': '二级目录'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_bar_code',
            field=models.CharField(max_length=64, verbose_name='条形码'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_detail',
            field=models.TextField(verbose_name='货物详情'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_img',
            field=models.CharField(max_length=128, verbose_name='货物图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_market_price',
            field=models.FloatField(default=0, verbose_name='货物市场价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_name',
            field=models.CharField(max_length=64, verbose_name='货物名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_price',
            field=models.FloatField(default=0, verbose_name='货物价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_store_num',
            field=models.IntegerField(default=10, verbose_name='库存量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitServer.GoodsTypeTwo', verbose_name='货物类型'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_unit',
            field=models.CharField(max_length=32, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='goodstypeone',
            name='g_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='一级名单'),
        ),
        migrations.AlterField(
            model_name='goodstypetwo',
            name='g_name',
            field=models.CharField(max_length=32, verbose_name='二级名单'),
        ),
    ]
