# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FruitServer', '0002_auto_20191022_1043'),
        ('FruitGP2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('is_select', models.BooleanField(default=True, verbose_name='是否选中')),
                ('c_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitServer.Goods', verbose_name='商品')),
            ],
        ),
        migrations.AlterModelOptions(
            name='fruituser',
            options={'verbose_name': '用户'},
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='f_age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='f_email',
            field=models.CharField(max_length=64, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='f_icon',
            field=models.CharField(max_length=128, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='f_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='f_password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='f_register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='f_sex',
            field=models.BooleanField(default=False, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='cart',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.FruitUser', verbose_name='用户'),
        ),
    ]
