# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-22 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FruitServer', '0002_auto_20191022_1043'),
        ('FruitGP2', '0002_auto_20191022_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=64, verbose_name='货物名')),
                ('g_price', models.FloatField(default=0, verbose_name='货物价格')),
                ('g_market_price', models.FloatField(default=0, verbose_name='货物市场价格')),
                ('g_unit', models.CharField(max_length=32, verbose_name='单位')),
                ('g_detail', models.TextField(verbose_name='货物详情')),
                ('g_img', models.CharField(max_length=128, verbose_name='货物图片')),
                ('g_bar_code', models.CharField(max_length=64, verbose_name='条形码')),
                ('g_store_num', models.IntegerField(default=10, verbose_name='库存量')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_status', models.IntegerField(default=0)),
                ('o_price', models.FloatField(default=0)),
                ('o_order_time', models.DateTimeField(auto_now_add=True)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.FruitUser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField(default=1)),
                ('o_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.Order')),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='g_ordergoods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.OrderGoods'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitServer.GoodsTypeTwo', verbose_name='货物类型'),
        ),
    ]
