# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FruitGP2', '0003_auto_20191022_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_comment', models.CharField(max_length=200, verbose_name='评论内容')),
                ('u_comment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('u_comment_add', models.CharField(max_length=256, verbose_name='追加评价')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '购物车'},
        ),
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'verbose_name': '商品信息'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单'},
        ),
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单商品'},
        ),
        migrations.AddField(
            model_name='usercomments',
            name='u_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.Order'),
        ),
    ]
