# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-23 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FruitGP2', '0004_auto_20191023_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomments',
            options={'verbose_name': '用户评价'},
        ),
    ]
