# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-23 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FruitGP2', '0005_auto_20191023_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_order_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_price',
            field=models.FloatField(default=0, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_status',
            field=models.IntegerField(default=0, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.FruitUser', verbose_name='用户'),
        ),
    ]
