# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-12-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRF3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=32)),
                ('b_content', models.TextField()),
                ('b_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DRF3.User')),
            ],
        ),
    ]
